version: "3"
services:
   mymongodb:
      image: mongo:5.0.2
      container_name: "mymongodb"
      ports:
      - 27017:27017
   tlt-testapp:
      image: tlttest-notes-app:1.2
      container_name: tlttest-notes-app
      ports:
      - 8080:8080
      links:
      - mymongodb